steps:

# Build the gke-deploy binary and put into the builder image.
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'init-container','--tag=latest', '.']


images:
- 'latest'

timeout: 6000s
